name: Compress All Images
on:
  workflow_dispatch:

jobs:
  build:
    name: Compress and Commit All Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get install -y pngquant jpegoptim

      - name: Compress PNGs
        run: find . -name "*.png" -not -path "./.git/*" -exec pngquant --force --ext .png --quality=65-80 {} \;

      - name: Compress JPEGs
        run: find . \( -name "*.jpg" -o -name "*.jpeg" \) -not -path "./.git/*" -exec jpegoptim --max=80 {} \;

      - name: Commit Compressed Images
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git diff --staged --quiet || git commit -m "Compress all existing images"
          git push
